[package]
name = "tui-realm-stdlib"
version = "0.6.2"
authors = ["Christian Visintin"]
edition = "2018"
categories = ["command-line-utilities"]
description = "Standard component library for tui-realm."
documentation = "https://docs.rs/tui-realm-stdlib"
homepage = "https://github.com/veeso/tui-realm-stdlib"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["tui", "terminal"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/veeso/tui-realm-stdlib"

[dependencies]
tuirealm = "0.6.0"
textwrap = "0.14.0"
unicode-width = "0.1.8"

[dev-dependencies]
crossterm = { version = "0.20" }
pretty_assertions = "0.7.2"
rand = "0.8.4"

# -- components

[[example]]
name = "bar-chart"
path = "examples/bar_chart.rs"

[[example]]
name = "canvas"
path = "examples/canvas.rs"

[[example]]
name = "chart"
path = "examples/chart.rs"

[[example]]
name = "checkbox"
path = "examples/checkbox.rs"

[[example]]
name = "input"
path = "examples/input.rs"

[[example]]
name = "label"
path = "examples/label.rs"

[[example]]
name = "line_gauge"
path = "examples/line_gauge.rs"

[[example]]
name = "list"
path = "examples/list.rs"

[[example]]
name = "paragraph"
path = "examples/paragraph.rs"

[[example]]
name = "progress_bar"
path = "examples/progress_bar.rs"

[[example]]
name = "radio"
path = "examples/radio.rs"

[[example]]
name = "select"
path = "examples/select.rs"

[[example]]
name = "span"
path = "examples/span.rs"

[[example]]
name = "sparkline"
path = "examples/sparkline.rs"

[[example]]
name = "table"
path = "examples/table.rs"

[[example]]
name = "textarea"
path = "examples/textarea.rs"
